import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import NavBar from '../components/NavBar'
import Showreel from '../components/Showreel'
import InstaCard from '../components/InstaCard'
import Gsk from '../components/Gsk'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wolffolins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <NavBar leftColor="rgb(255,235,0)" rightColor="rgb(255,235,0)" />
      {/* <ScrollingSection /> */}
      <Showreel />
      <InstaCard />
      <Gsk />
      </main>
    </div>
  )
}

export default Home
